algo:
  name: ppo 
  ent_coef: 0.01
  clip_range: 0.1
  vf_coef: 0.5
  learning_rate: 1e-4
  #learning_rate:  5e-5
  #learning_rate: -1 #this turns on scheduler
  n_steps: 2048 #n_steps means n_steps per env before update
#goal_type: rand_dir 
goal_type: fixed_dir
hidden_sz: 256
num_envs: 8
resume: ""
out: ./log
seed: 0
