algo:
  name: sac
  learning_rate: 1e-4
  action_noise_sigma: 0.1
  weight_decay: 0.00 #not part of standard PPO
  batch_size: 256
  buffer_size: 250000
problem:
  terrain_type: "perlin" #options are "bands", "perlin", "flat"
total_timesteps: 25e6
#frozen_cnn: "../encoder_frozen/encoder_epoch_53" #this model has been trained with snoise
frozen_cnn: ""
goal_type: fixed_dir
hidden_sz: 256
num_envs: 20
resume: ""
out: ./log
seed: 10
