algo:
  name: ppo 
  ent_coef: 0.02
  clip_range: 0.1
  vf_coef: 0.5
  learning_rate: 5e-5
  n_steps: 2000 #n_steps means n_steps per env before update
goal_type: directional 
hidden_sz: 512
num_envs: 1
resume: ""
out: ./log
seed: 0
