algo:
  name: ppo 
  ent_coef: 0.005
  clip_range: 0.1
  vf_coef: 0.5
  #learning_rate: 1e-4
  learning_rate: 5e-5
  #learning_rate: -1 #this turns on scheduler
  n_steps: 2048 #n_steps means n_steps per env before update
  weight_decay: 0.01 #not part of standard PPO
total_timesteps: 10e6
frozen_cnn: "../encoder_frozen/encoder_epoch_38_pnoise_and_snoise"
goal_type: fixed_dir
hidden_sz: 128
num_envs: 8
resume: ""
out: ./log
seed: 10
